//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyCanTin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public int IDNV { get; set; }
        public System.DateTime NGAYLAM { get; set; }
        public string CATRUC { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
