//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyCanTin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int IDKH { get; set; }
        [Required(ErrorMessage = "Họ tên không được để trống")]
        public string TENKH { get; set; }
        [Required(ErrorMessage = "Giới tính không được để trống")]
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        [Required(ErrorMessage = "SĐT không được để trống")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "Email không được để trống")]
        [EmailAddress(ErrorMessage = "Địa chỉ email không hợp lệ")]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Tài khoản không được bỏ trống")]
        public string TAIKHOAN { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được bỏ trống")]
        public string MATKHAU { get; set; }
        [Required(ErrorMessage = "Trường này không được bỏ trống")]
        [Compare("MATKHAU", ErrorMessage = "Mật khẩu không khớp")]
        public string NHAPLAIMK { get; set; }


       
        public string LAYLAIMK { get; set; }

        [Required(ErrorMessage = "Trường này không được bỏ trống")]
        [Compare("LAYLAIMK", ErrorMessage = "Mật khẩu cũ không khớp")]
        public string MATKHAUCU { get; set; }
        [Required(ErrorMessage = "Trường này không được bỏ trống")]
        public string MATKHAUMOI { get; set; }
        [Required(ErrorMessage = "Trường này không được bỏ trống")]
        [Compare("MATKHAUMOI", ErrorMessage = "Mật khẩu không khớp")]
        public string NHAPLAIMKMOI { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
