//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyCanTin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANG
    {
        public int IDSP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public Nullable<int> IDNCC { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
